### ISSUE TITLE
Add timestamp to responses

### ISSUE THREAD

**Issue by Lynx1820** [The-Percentage-Project/survey-engine#60]

**Comment by dtriana** [comment]
@Lynx1820 I added some logic on the API controller to add the current date/time in EST to the survey model, then modified the schema.js to add the timestamp property, tested locally with a survey and verified on the DB that the property was in fact added with the expected value,

![image](https://user-images.githubusercontent.com/15910899/98732221-db712e80-236c-11eb-8477-3bbfb45f097b.png)

Anything else I should check?

**Comment by Lynx1820** [comment]
@dtriana That's looks great! Nope, once you have merged your code, we can close this issue.

**Comment by gfting** [comment]
Closed by #65. Thank you!
